/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BandCalculatorRouteImport } from './routes/band-calculator'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as ModelAnswersRouteImport } from './routes/model-answers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TaskPracticeRouteImport } from './routes/task-practice'
import { Route as TestRouteImport } from './routes/test'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as WritingGeneratorRouteImport } from './routes/writing-generator'
import { Route as MockTestMockIdRouteImport } from './routes/mock-test_.$mockId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BandCalculatorRoute = BandCalculatorRouteImport.update({
  id: '/band-calculator',
  path: '/band-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelAnswersRoute = ModelAnswersRouteImport.update({
  id: '/model-answers',
  path: '/model-answers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskPracticeRoute = TaskPracticeRouteImport.update({
  id: '/task-practice',
  path: '/task-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingGeneratorRoute = WritingGeneratorRouteImport.update({
  id: '/writing-generator',
  path: '/writing-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestMockIdRoute = MockTestMockIdRouteImport.update({
  id: '/mock-test_/$mockId',
  path: '/mock-test/$mockId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/band-calculator': typeof BandCalculatorRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mock-test': typeof MockTestRoute
  '/model-answers': typeof ModelAnswersRoute
  '/notifications': typeof NotificationsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/pronunciation': typeof PronunciationRoute
  '/register': typeof RegisterRoute
  '/requirements': typeof RequirementsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/task-practice': typeof TaskPracticeRoute
  '/test': typeof TestRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-generator': typeof WritingGeneratorRoute
  '/mock-test/$mockId': typeof MockTestMockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/band-calculator': typeof BandCalculatorRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mock-test': typeof MockTestRoute
  '/model-answers': typeof ModelAnswersRoute
  '/notifications': typeof NotificationsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/pronunciation': typeof PronunciationRoute
  '/register': typeof RegisterRoute
  '/requirements': typeof RequirementsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/task-practice': typeof TaskPracticeRoute
  '/test': typeof TestRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-generator': typeof WritingGeneratorRoute
  '/mock-test/$mockId': typeof MockTestMockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/band-calculator': typeof BandCalculatorRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mock-test': typeof MockTestRoute
  '/model-answers': typeof ModelAnswersRoute
  '/notifications': typeof NotificationsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/pronunciation': typeof PronunciationRoute
  '/register': typeof RegisterRoute
  '/requirements': typeof RequirementsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/task-practice': typeof TaskPracticeRoute
  '/test': typeof TestRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing-generator': typeof WritingGeneratorRoute
  '/mock-test_/$mockId': typeof MockTestMockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/band-calculator'
    | '/community'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/mock-test'
    | '/model-answers'
    | '/notifications'
    | '/practice'
    | '/profile'
    | '/pronunciation'
    | '/register'
    | '/requirements'
    | '/resources'
    | '/settings'
    | '/task-practice'
    | '/test'
    | '/vocabulary'
    | '/writing-generator'
    | '/mock-test/$mockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/band-calculator'
    | '/community'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/mock-test'
    | '/model-answers'
    | '/notifications'
    | '/practice'
    | '/profile'
    | '/pronunciation'
    | '/register'
    | '/requirements'
    | '/resources'
    | '/settings'
    | '/task-practice'
    | '/test'
    | '/vocabulary'
    | '/writing-generator'
    | '/mock-test/$mockId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/band-calculator'
    | '/community'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/mock-test'
    | '/model-answers'
    | '/notifications'
    | '/practice'
    | '/profile'
    | '/pronunciation'
    | '/register'
    | '/requirements'
    | '/resources'
    | '/settings'
    | '/task-practice'
    | '/test'
    | '/vocabulary'
    | '/writing-generator'
    | '/mock-test_/$mockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BandCalculatorRoute: typeof BandCalculatorRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MockTestRoute: typeof MockTestRoute
  ModelAnswersRoute: typeof ModelAnswersRoute
  NotificationsRoute: typeof NotificationsRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  PronunciationRoute: typeof PronunciationRoute
  RegisterRoute: typeof RegisterRoute
  RequirementsRoute: typeof RequirementsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  TaskPracticeRoute: typeof TaskPracticeRoute
  TestRoute: typeof TestRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingGeneratorRoute: typeof WritingGeneratorRoute
  MockTestMockIdRoute: typeof MockTestMockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band-calculator': {
      id: '/band-calculator'
      path: '/band-calculator'
      fullPath: '/band-calculator'
      preLoaderRoute: typeof BandCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-answers': {
      id: '/model-answers'
      path: '/model-answers'
      fullPath: '/model-answers'
      preLoaderRoute: typeof ModelAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-practice': {
      id: '/task-practice'
      path: '/task-practice'
      fullPath: '/task-practice'
      preLoaderRoute: typeof TaskPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing-generator': {
      id: '/writing-generator'
      path: '/writing-generator'
      fullPath: '/writing-generator'
      preLoaderRoute: typeof WritingGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test_/$mockId': {
      id: '/mock-test_/$mockId'
      path: '/mock-test/$mockId'
      fullPath: '/mock-test/$mockId'
      preLoaderRoute: typeof MockTestMockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  BandCalculatorRoute: BandCalculatorRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MockTestRoute: MockTestRoute,
  ModelAnswersRoute: ModelAnswersRoute,
  NotificationsRoute: NotificationsRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  PronunciationRoute: PronunciationRoute,
  RegisterRoute: RegisterRoute,
  RequirementsRoute: RequirementsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  TaskPracticeRoute: TaskPracticeRoute,
  TestRoute: TestRoute,
  VocabularyRoute: VocabularyRoute,
  WritingGeneratorRoute: WritingGeneratorRoute,
  MockTestMockIdRoute: MockTestMockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
